version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pip install awscli aws-sam-cli
      - sam package --template-file "$(CODEBUILD_SRC_DIR)"/template.yaml --s3-bucket idexceldemo-sam --output-template-file "$(CODEBUILD_SRC_DIR)"/packaged.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml
  discard-paths: yes
