version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pip install awscli aws-sam-cli
      - sam package --template-file sam-app/template.yaml --s3-bucket idexceldemo-sam --output-template-file sam-app/packaged.yaml
artifacts:
  type: zip
  files:
    - sam-app/template.yaml
    - sam-app/packaged.yaml
  discard-paths: yes
