version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pip install awscli aws-sam-cli
  #    - mkdir build-output
  #    - cp -R sam-app/ build-output
      - sam package --template-file template.yaml --s3-bucket idexceldemo-sam --output-template-file packaged.yaml
 # post_build:
 #   commands:
 ##     - mv build-output/**/* ./
 #     - mv build-output/* ./
 #     - rm -R build-output *.yml README* .git*

artifacts:
  type: zip
  files:
    - '**/*'
  discard-paths: yes
